### ISSUE TITLE
Spawn of creeper, zombies and skeletons in the nether

### ISSUE THREAD

**Issue by MyLittleYery** [ItsBlackGear/CaveBiomeAPI#19] opened 2021-11-05 00:20 UTC
With "Caves and Cliffs backport 7.0" and "CavebiomeAPI 1.4.1" versions overworld creatures are generated on the nether, whether they are from minecraft vanilla such as creepers, bats and zombies or from mods, such as cockroaches from Alex's Mobs.

**Comment by ItsBlackGear** [comment] 2021-11-05 05:46
Are you sure that it's caused by us? We don't touch the nether and also we
use a special condition in the code that prevents generating features in
the nether, the end and void

**Comment by MyLittleYery** [comment] 2021-11-05 08:36
Yes, I tested the mods one by one and it is the one that generated them.  I also tried Caves and Cliffs Backport 7.0 with CavebiomeAPI 1.3.7 and they generated anyway.  I currently use CaCB 6.3 and API 1.3.7 and everything works fine.

**Comment by ItsBlackGear** [comment] 2021-11-05 14:56
Tried to update the api? The current version is 1.4.1

**Comment by MyLittleYery** [comment] 2021-11-05 15:47
Yes, I have tried version 1.4.1 and 1.3.7 and the same thing happened

**Comment by ItsBlackGear** [comment] 2021-11-05 15:59
That's weird! I just tested it and i found nothing, i'll ask in my discord
if anyone else has gotten anything similar

**Comment by ItsBlackGear** [comment] 2021-11-05 16:05
By any chance happen to have some screenshots?

**Comment by ItsBlackGear** [comment] 2021-11-13 20:41
i'll close this issue due lack of information and no results in attempt of replicate

**Closed as completed by ItsBlackGear** 2021-11-13 20:41 UTC
